# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 282f84d27d71c494135d7a57c06a195cdd04cbf2a2d2d7e4e9d7f4ca610207997277b26743927d0a074448403f5c60dfbccf05f56fa7c856be51c209fa695ccf

test:
  secret_key_base: eb50c01c47ca4cbed874750c0fb08b645c06cebf04d086de11fde414929212fe06c51143b4b70f56d031a9448f8d12281af64c397ceb58bbe1c21c9a13d8a948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9164811e967da3984bb74735c1ab573f3bd322cf0093198a78b7ac3f35c2118d1a6a6c1ffc9cd61902421f3a5d83e347aeb12bc6be367b0868cee294926f181d
